application: atcoinorg
version: development
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: atcoinorg.wsgi.application

includes:
- static.yaml

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'atcoinorg.settings'

libraries:
- name: PIL
  version: "latest"

- name: MySQLdb
  version: "latest"

skip_files:
- manage.py
- requirements.txt
- (.*)\.pyc
- (.*)\.db
- (.*)\-info
- README.md
- .gitignore
- ^(.*/)?.*.idea/.*